/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Cristian Daniel
 */
public class PantallaCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaCalculadora.class.getName());

    /**
     * Creates new form PantallaCalculadora
     */
    public PantallaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btmCuadrado = new javax.swing.JButton();
        btmRectangulo = new javax.swing.JButton();
        btmRombo = new javax.swing.JButton();
        btmRomboide = new javax.swing.JButton();
        btmParalelogramo = new javax.swing.JButton();
        btmTriangulo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLado1 = new javax.swing.JTextPane();
        txtLado2 = new javax.swing.JScrollPane();
        txtLado = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLado3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLado4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAltura = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBase = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDiagonal1 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtDiagonal2 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtBaseMenor = new javax.swing.JTextPane();
        btmPerimetro = new javax.swing.JButton();
        btmArea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ELIJA SU FIGURA PARA CALCULAR EL AREA"));

        btmCuadrado.setText("CUADRADO");
        btmCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCuadradoActionPerformed(evt);
            }
        });

        btmRectangulo.setText("RECTANGULO");
        btmRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRectanguloActionPerformed(evt);
            }
        });

        btmRombo.setText("ROMBO");
        btmRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRomboActionPerformed(evt);
            }
        });

        btmRomboide.setText("ROMBOIDE");
        btmRomboide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRomboideActionPerformed(evt);
            }
        });

        btmParalelogramo.setText("PARALELOGRAMO");
        btmParalelogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmParalelogramoActionPerformed(evt);
            }
        });

        btmTriangulo.setText("TRIANGULO");
        btmTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTrianguloActionPerformed(evt);
            }
        });

        txtLado1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE LADO 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtLado1.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane1.setViewportView(txtLado1);

        txtLado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE LADO 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtLado.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        txtLado2.setViewportView(txtLado);

        txtLado3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASE ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtLado3.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane3.setViewportView(txtLado3);

        txtLado4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Altura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtLado4.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane4.setViewportView(txtLado4);

        txtAltura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALTURA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtAltura.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane5.setViewportView(txtAltura);

        txtBase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtBase.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane6.setViewportView(txtBase);

        txtDiagonal1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGONAL:1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtDiagonal1.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane7.setViewportView(txtDiagonal1);

        txtDiagonal2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGONAL:2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtDiagonal2.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane8.setViewportView(txtDiagonal2);

        txtBaseMenor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASE MENOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 8))); // NOI18N
        txtBaseMenor.setFont(new java.awt.Font("Segoe UI Light", 1, 8)); // NOI18N
        jScrollPane9.setViewportView(txtBaseMenor);

        btmPerimetro.setText("Perimetro");

        btmArea.setText("Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btmRomboide)
                                    .addComponent(btmCuadrado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btmParalelogramo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btmRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btmRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btmTriangulo)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btmPerimetro)
                        .addGap(53, 53, 53)
                        .addComponent(btmArea)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCuadrado)
                    .addComponent(btmRectangulo)
                    .addComponent(btmRombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmRomboide)
                    .addComponent(btmParalelogramo)
                    .addComponent(btmTriangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane5))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmPerimetro)
                    .addComponent(btmArea))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmRectanguloActionPerformed

    private void btmRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmRomboActionPerformed

    private void btmRomboideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRomboideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmRomboideActionPerformed

    private void btmParalelogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmParalelogramoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmParalelogramoActionPerformed

    private void btmCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmCuadradoActionPerformed

    private void btmTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btmArea;
    public javax.swing.JButton btmCuadrado;
    public javax.swing.JButton btmParalelogramo;
    public javax.swing.JButton btmPerimetro;
    public javax.swing.JButton btmRectangulo;
    public javax.swing.JButton btmRombo;
    public javax.swing.JButton btmRomboide;
    public javax.swing.JButton btmTriangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTextPane txtAltura;
    public javax.swing.JTextPane txtBase;
    public javax.swing.JTextPane txtBaseMenor;
    public javax.swing.JTextPane txtDiagonal1;
    public javax.swing.JTextPane txtDiagonal2;
    public javax.swing.JTextPane txtLado;
    public javax.swing.JTextPane txtLado1;
    private javax.swing.JScrollPane txtLado2;
    public javax.swing.JTextPane txtLado3;
    public javax.swing.JTextPane txtLado4;
    // End of variables declaration//GEN-END:variables
}
