/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Kleyber
 */
public class JFRegistrarCuidador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFRegistrarCuidador.class.getName());

    /**
     * Creates new form JFRegistrarCuidador
     */
    public JFRegistrarCuidador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCuidador = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNivelDeExperiencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRazasManejo = new javax.swing.JTextField();
        btnRegistrarCuidador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Registrar Cuidador");

        jLabel2.setText("Nombre");

        txtNombreCuidador.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreCuidador.setText("Nombre del Cuidador");
        txtNombreCuidador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreCuidador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreCuidadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreCuidadorFocusLost(evt);
            }
        });

        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ej: 1090123456");
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addActionListener(this::txtCedulaActionPerformed);

        jLabel3.setText("Cedula");

        jLabel4.setText("Nivel De Experiencia");

        txtNivelDeExperiencia.setForeground(new java.awt.Color(153, 153, 153));
        txtNivelDeExperiencia.setText("1, 2 ,3 ...");
        txtNivelDeExperiencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNivelDeExperienciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNivelDeExperienciaFocusLost(evt);
            }
        });

        jLabel5.setText("Razas que puede manejar");

        txtRazasManejo.setForeground(new java.awt.Color(153, 153, 153));
        txtRazasManejo.setText("Separadas por /");
        txtRazasManejo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazasManejoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazasManejoFocusLost(evt);
            }
        });

        btnRegistrarCuidador.setText("Registrar Cuidador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreCuidador)
                                    .addComponent(txtCedula)
                                    .addComponent(txtNivelDeExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(txtRazasManejo)))
                            .addComponent(btnRegistrarCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNivelDeExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRazasManejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnRegistrarCuidador)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCuidadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCuidadorFocusGained
        // Si el texto es la sugerencia, lo borramos y ponemos la letra en negro
        if (txtNombreCuidador.getText().equals("Nombre del Cuidador")) {
            txtNombreCuidador.setText("");
            txtNombreCuidador.setForeground(new java.awt.Color(0, 0, 0)); // Color Negro
        }
    }//GEN-LAST:event_txtNombreCuidadorFocusGained

    private void txtNombreCuidadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCuidadorFocusLost
        if (txtNombreCuidador.getText().isEmpty()) {
            txtNombreCuidador.setForeground(new java.awt.Color(153, 153, 153)); // Color Gris
            txtNombreCuidador.setText("Nombre del Cuidador");
        }
    }//GEN-LAST:event_txtNombreCuidadorFocusLost

    private void txtCedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusGained
        if (txtCedula.getText().equals("Ej: 1090123456")) {
            txtCedula.setText("");
            txtCedula.setForeground(new java.awt.Color(0, 0, 0)); // Color Negro
        }
    }//GEN-LAST:event_txtCedulaFocusGained

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        if (txtCedula.getText().isEmpty()) {
            txtCedula.setForeground(new java.awt.Color(153, 153, 153)); // Color Gris
            txtCedula.setText("Ej: 1090123456");
        }
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtNivelDeExperienciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNivelDeExperienciaFocusGained
        if (txtNivelDeExperiencia.getText().equals("1, 2 ,3 ...")) {
            txtNivelDeExperiencia.setText("");
            txtNivelDeExperiencia.setForeground(new java.awt.Color(0, 0, 0)); // Color Negro
        }
    }//GEN-LAST:event_txtNivelDeExperienciaFocusGained

    private void txtNivelDeExperienciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNivelDeExperienciaFocusLost
        if (txtNivelDeExperiencia.getText().isEmpty()) {
            txtNivelDeExperiencia.setForeground(new java.awt.Color(153, 153, 153)); // Color Gris
            txtNivelDeExperiencia.setText("1, 2 ,3 ...");
        }
    }//GEN-LAST:event_txtNivelDeExperienciaFocusLost

    private void txtRazasManejoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazasManejoFocusGained
        if (txtRazasManejo.getText().equals("Separadas por /")) {
            txtRazasManejo.setText("");
            txtRazasManejo.setForeground(new java.awt.Color(0, 0, 0)); // Color Negro
        }
    }//GEN-LAST:event_txtRazasManejoFocusGained

    private void txtRazasManejoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazasManejoFocusLost
        if (txtRazasManejo.getText().isEmpty()) {
            txtRazasManejo.setForeground(new java.awt.Color(153, 153, 153));
            txtRazasManejo.setText("Separadas por /");
        }
    }//GEN-LAST:event_txtRazasManejoFocusLost

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFRegistrarCuidador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarCuidador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtNivelDeExperiencia;
    public javax.swing.JTextField txtNombreCuidador;
    public javax.swing.JTextField txtRazasManejo;
    // End of variables declaration//GEN-END:variables
}
